### PR TITLE
Fixed format for storing Polygons

### PR DESCRIPTION
**Pull request by petermein**
Polygons where defined as POLYGON((0 0, 10 0),(10 0, 10 10)) but the correct format is a collection of points. POLYGON(0 0, 10 0, 10 0, 10 10))

### CODE REVIEW

**Comment by phaza** [comment]
I don't think this is correct.
Both [wikipedia][1] and [postgis docs][2] lists Polygons as a collection of linestrings.

`POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))`

[1]: http://en.wikipedia.org/wiki/Well-known_text#Geometric_objects
[2]: http://postgis.net/docs/ST_Polygon.html

**Comment by phaza** [comment]
You're absolutely right, but please make a pull request against current master.

**Comment by petermein** [comment]
Done

**Comment by phaza** [comment]
Remember to update the tests as well. Currently they are failing.

**Comment by petermein** [comment]
Ai, this is a question of how you wanna build a polygon. In you're design a single linestring should create a closed polygon. This is fine. 

On the other hand i was in assuming that you would build a polygon by giving a closed set op linestrings. Maybe for a future implementation.

**Pull request closed without merging**
