### PR TITLE
Allow Geometry Columns and Differing SRID

### PR DESCRIPTION
**Pull request by stevegoddard**

### CODE REVIEW

**Comment by phaza** [comment]
Can you please make sure all tests are passing?
Also, can you turn GEOGRAPHY and GEOMETRY into const values (perhaps on the blueprint?) To avoid the possibility or spelling errors.

**Comment by stevegoddard** [comment]
Not sure why the tests are failing – will investigate.

Not quite sure what you mean by turning the GEOMETRY and GEOGRAPHY in to constants. Could you give me an example or point me in the right direction?

Thanks
Steve

**Comment by stevegoddard** [comment]
Ok - got the tests all passing fine locally. They are failing on github with an error that appears to be with the Bosnadev package:

    1) ConnectionFactoryBaseTest::testMakeCallsCreateConnection
    Declaration of Bosnadev\Database\Connectors\ConnectionFactory::createConnection() should be compatible with Illuminate\Database\Connectors\ConnectionFactory::createConnection($driver, $connection, $database, $prefix = '', array $config = Array)

Any ideas??

I've done some more reading on constants. It seems a lot of complexity when a in_array check (which is what currently happens) might be quicker and simpler? But maybe I'm overcomplicating things?

**Comment by stevegoddard** [comment]
Will cancel this and try again with a version 2 branch.

**Pull request closed without merging**
